name: Test and Release

on:
  push:
    branches:
      - "*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-**"
  pull_request:

jobs:
  check-and-lint:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Lint source code
        run: npm run lint

      - name: Test package files
        run: npm run test:package

  adapter-tests:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    needs:
      - check-and-lint

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x, 26.x]
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests (unix only)
        if: runner.os != 'Windows'
        run: DEBUG=testing:* npm run test:integration

      - name: Run integration tests (windows only)
        if: runner.os == 'Windows'
        run: |
          set DEBUG=testing:*
          npm run test:integration