name: Test and Release

on:
  push:
    branches:
      - "*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-**"
  pull_request:

jobs:
  check-and-lint:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use Node.js 26.x
        uses: actions/setup-node@v7
        with:
          node-version: 26.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint source code
        run: npm run lint

      - name: Test package files
        run: npm run test:package

  adapter-tests:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    needs:
      - check-and-lint

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22.x
          - 24.x
          - 26.x
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        shell: bash
        env:
          DEBUG: testing:*
        run: npm run test:integration
